Parameters:
  S3BucketName:
    Type: String

Resources:
  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref S3AccessRole

  S3AccessRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole

  RolePolicies:
    Type: AWS::IAM::Policy
    DependsOn:
      - Arm64Instance
    Properties:
      PolicyName: S3FullAccessPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: 's3:*'
            Resource: '*'
          - Effect: Allow
            Action: 'ec2:CreateTags'
            Resource: '*'
      Roles:
        - !Ref S3AccessRole


  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22

  Arm64Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: ec2-keypair
      InstanceType: t4g.micro
      ImageId: ami-087fa126bfdebc5c3  # Ubuntu18.04 Arm64
      IamInstanceProfile: !Ref EC2InstanceProfile
      SecurityGroups:
        - !Ref SSHSecurityGroup
      Tags:
        - Key: Name
          Value: arm64-ubuntu
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          az=$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone)
          region=${!az%%?}
          instance_id=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
          apt update
          apt install -y awscli

          aws ec2 create-tags --resources $instance_id --region $region --tags Key=Status,Value=CONFIGURING
          apt remove lxd-client -y
          snap install lxd
          lxd init --auto
          snap install snapcraft --classic

          aws ec2 create-tags --resources $instance_id --region $region --tags Key=Status,Value=SNAPPING
          mkdir -p /tmp/robomaker_snap
          cd tmp/robomaker_snap
          aws s3 cp s3://${S3BucketName}/src src/ --recursive
          aws s3 cp s3://${S3BucketName}/snap snap/ --recursive
          #snapcraft --use-lxd
          #aws s3 cp *.snap s3://${S3BucketName}/

          aws ec2 create-tags --resources $instance_id --region $region --tags Key=Status,Value=COMPLETE
          echo 'Exiting user data script'

          echo {AWS::Region}
          echo {Arm64Instance.AvailabilityZone}

Outputs:
  InstanceId:
    Value: !Ref Arm64Instance

