name: hello-world
version: '0.1'
summary: RoboMaker Hello World
description: |
  AWS RoboMaker robot package with a rotating Turtlebot3

base: core18
grade: devel 
confinement: devmode

parts:
  robot-ws:
    plugin: catkin
    source: .
    build-packages: [lsb-release]
    
apps:
  launch:
    command: rosrun hello_world talker.py
    plugs: [network, network-bind]